
data:
  dir: "../data/"
  audio: "audio/"
  meta: "metadata/"
  user: "user/"

search:
  featureset: "gtzan"
  system: "dummy"
  dbbackend: "builtin"

debugmode: True

hellostring: "<b>From inside the virgin woods was born Macunaima, hero of our people!</b>"
